"""Build reviewed quarter-beat anchors from PDF columns; no audio/lyric writes.
Input: local audit columns and song. Indices reflect visual rhythm review.
"""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2]
s=json.loads((R/'public/demo/song.json').read_text());cols=json.loads((R/'docs/experiments/beat-anchor-audit/columns.json').read_text())
indices={5:[0,2,4,6],7:[0,2,3,6],8:[0,2,6,9],12:[0,2,6,9],16:[0,2,6,9],24:[0,2,5,8],28:[0,2,5,7],32:[0,2,6,9],36:[0,2,6,8],39:[0,2,6,8],40:[0,3,7,8],41:[0,2,5,7],42:[0,2,5,7],45:[0,2,5,7],46:[0,2,5,7],48:[0,1,4,7],56:[0,2,6,8],60:[0,2,6,9],63:[0,2,5,9],64:[0,2,6,9],68:[0,2,6,8],72:[0,3,6,9],80:[0,3,7,10],83:[0,3,5,7],84:[0,2,4,6,9],88:[0,2,6,8],90:[0,2,6,8],91:[0,3,7,11],92:[0,2,5,8],94:[0,2,5,8],96:[0,2,5,8],100:[0,2,5,8],104:[0,2,6,10],106:[0,2,6,9],107:[0,1,2,3],108:[0,2,4,5],109:[0,1,2,3]}
width={'œ':6.54,'x':6.01,'o':4.79,'Œ':5.88,'‰':5.88,'≈':5.88}
out={}
for bar,ii in indices.items():
 r=next(r for r in s['regions'] if r['id']==f'r{bar}');c=cols[str(bar)];points=[]
 for i in ii:
  col=c[i];glyph=next((g for g,y in col['glyphs'] if g=='œ'),col['glyphs'][0][0]);points.append(round(col['x']+width[glyph]/2,3))
 xs=[(x/612-r['x'])/r['w'] for x in points]+[1]
 assert all(0<=x<y<=1 for x,y in zip(xs,xs[1:])),bar
 out[r['id']]={'page':r['page'],'x':r['x'],'y':r['y'],'w':r['w'],'h':r['h'],'points':points,'kind':'notes-and-rests'}
for bar in [1,2,3,4,6,43,44,47,51,103,110]:
 r=next(r for r in s['regions'] if r['id']==f'r{bar}');out[r['id']]={k:r[k] for k in ['page','x','y','w','h']};out[r['id']].update(points=[],kind='symbolic')
(R/'src/score-anchor-data.ts').write_text('// Reviewed PDF page coordinates in points; generated by scripts/score/build-anchor-corrections.py.\nexport const scoreAnchorCorrections = '+json.dumps(out,ensure_ascii=False,indent=2)+' as const;\n')
print(len(out),'regions',len(indices),'note/rest patterns')
